### PR TITLE
Clean-up Logic for Adding and Removing Log-files.

### PR DESCRIPTION
**Pull request by gmanjames**
Clean up and auxiliary functions for handling the upload of an additional log-file. Also added ability to remove a second log-file.

### CODE REVIEW

**Review by kylefinter — DISMISSED** [review]

**Comment by kylefinter** [comment]
I will say I just checked out your branch and at least on my computer the X button to remove a log file is not working when there is only a single uploaded log file.

**Comment by gmanjames** [comment]
@kylefinter That is how it is supposed to behave like we discussed. When there is only one file uploaded there shouldn't be a need to remove it.

**Comment by kylefinter** [comment]
Then maybe we need to hide the X button when there is only one log file. It doesn't make sense to display it if the user can't interact with it.

**Comment by gmanjames** [comment]
Yeah I am hoping to have separate styles for 'disabled' ready in the next commit. So something like .rm-file[data-state='disabled'] etc. etc.

**Comment by kylefinter** [comment]
Ok sounds good.

**Review by kylefinter — APPROVED** [review]

**Comment by gmanjames** [comment]
I think I will just leave this pull request up until I get those changes instead of merging into master now. That way I won't have to make a separate one for those tweaks.

**Comment by gmanjames** [comment]
Alright the last commit there should take care of things. I am going to merge this in now.
@kylefinter @JesseStew @BSpatz @MichaelLB11

**Pull request merged**
