### PR TITLE
GUI polish. Playback time bug fixes. Additional playback controls. Begin finalizing code formatting.

### PR DESCRIPTION
**Pull request by gmanjames**
There are quite a lot of changes here. Firstly, I polished/reorganized some of the playback and model controls. Added an indicator for which animation is active. Added play all button. Added pause all button. Made all range type inputs consistent in styling. Added input box for range type controls to allow the user to type a value (like the prototype visualizer). Added 'pages' for the playback controls section. Added an image for the main play pause button. Began formatting code in 'controls'.

### CODE REVIEW

**Comment by kylefinter** [comment]
I got an idea that might be cool. What if when the mouse moves off of the window that selects the colors and textures the menu auto hides?

**Comment by gmanjames** [comment]
@kylefinter I think that would be quite nice. I'll try to get that added to this pull request.

**Comment by kylefinter** [comment]
I'm working on keeping the transparency and color to save their state to an internal object. Then I'll make a commit on this branch to keep it in the same pull request.

**Review by kylefinter — APPROVED** [review]
It all looks good. I've finished adding my code. There might still be one or two spacing issues but I think I got most of them resolved.

**Pull request merged**
